# Generated by Django 3.2 on 2022-08-26 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preco')),
                ('estoque', models.IntegerField(verbose_name='Qtd no Estoque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='core', verbose_name='IMG')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_produto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
