# Generated by Django 3.2 on 2022-09-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='post',
            field=models.CharField(default=1, max_length=200, verbose_name='Post'),
            preserve_default=False,
        ),
    ]
