# Generated by Django 3.2 on 2022-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='post',
            new_name='postagem',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='core', verbose_name='IMG'),
        ),
    ]
