# Generated by Django 3.2 on 2022-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd no Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='postagem',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preco'),
        ),
    ]
