# Generated by Django 3.2 on 2022-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_produto_tempo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='postagem',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Post'),
        ),
    ]
